version: '3.3'

services:
    rlab-api:
        build:
          context: .
          target: development
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
        ports:
          - 7000:7000
          - 9229:9229
        command: npm run start:dev
        env_file:
          - .env
        depends_on:
          - mysql
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'remotelabdb'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'strongpassword'
            MYSQL_ROOT_PASSWORD: 'strongpassword'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db: