name: Actions on new code
on: [pull_request]
jobs:
  lint:
    name: Running ESLint
    runs-on: ubuntu-20.04
    if: github.head_ref != 'master' && github.head_ref != 'demo'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: c-hive/gha-npm-cache@v1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: Get files diff
        id: diff
        run: |
          git fetch --progress origin ${{ github.base_ref }}
          tsFiles=$(git diff origin/${{ github.base_ref }} --diff-filter=ACM --name-only -- '*.ts' | xargs)
          echo "::set-output name=tsFiles::$(echo $tsFiles)"
          echo "::set-output name=eslintFlags::--config=.eslintrc.js $(echo $tsFiles)"
      - name: Run ESLint (TS)
        if: ${{ steps.diff.outputs.tsFiles }}
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: ${{ steps.diff.outputs.eslintFlags }}
          fail_on_error: false
          reporter: github-pr-check
  test:
    name: Unit tests
    needs: lint
    runs-on: ubuntu-20.04
    if: github.head_ref != 'master' && github.head_ref != 'demo'
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          .bin/cbu-run-tests
